# Most and least revenue generated by an order:

import sqlite3

conn = sqlite3.connect('your_database.db')
cursor = conn.cursor()

cursor.execute("SELECT MAX(OrderAmount) FROM orders")
max_revenue = cursor.fetchone()[0]

cursor.execute("SELECT MIN(OrderAmount) FROM orders")
min_revenue = cursor.fetchone()[0]

cursor.close()
conn.close()

print(f"Most revenue from a single order: {max_revenue}")
print(f"Least revenue from a single order: {min_revenue}")
